# Base configs
baseurl: "https://grvsion.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Gaurav Kshirsagar"
subtitle: "Capturing one moment at a time!"
author: "Gaurav Kshirsagar"
header:
 title: "Photography"
 subtitle: "by Gaurav Kshirsagar"
footer:
 name: "Hey there, my name is Gaurav"
 bio: "I am a data scientist and a art lover from India. I do photography as a hobby"
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/gk5894"
  instagram: "https://www.instagram.com/grvsion"
  linkedin: "https://in.linkedin.com/in/gauravksh"
  github: "https://www.github.com/grvsion"
